serviceName: frontend-service
serviceDir: frontend-service
language: node

installCommand: npm install
buildCommand: ""
testCommand: npm test

nodeEnv: production

sonarProjectKey: frontend-service
sonarProjectName: frontend-service
